name: Release
on:
  schedule:
    - cron: "0 9 * * 1-5"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm audit --omit=dev
      - run: npm ci
      # TODO: Check if has changes
      - run: npm run lint
      - run: npm test
      - run: npm run build
      # TODO: Create release
